version: '3.7'

services:
  shopper_backend:
    container_name: shopper_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - shopper_network
  db:
    image: postgres:15-alpine
    container_name: shopper_db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopper_network

networks:
  shopper_network:
    name: shopper_network
    driver: bridge

volumes:
  postgres_data:
    driver: local