export enum MeasuresRequestErrors {
  INVALID_DATA = "INVALID_DATA",
  DOUBLE_REPORT = "DOUBLE_REPORT",
  INVALID_TYPE = "INVALID_TYPE",
  MEASURE_NOT_FOUND = "MEASURE_NOT_FOUND",
  CONFIRMATION_DUPLICATE = "CONFIRMATION_DUPLICATE",
}
